alleyinteractive/es-wp-query

class-es-wp-tax-query.php

If a map (explicitly numbered) array is passed in as part of a tax__in query we generate a broken ES query as it gets turned into an object not array in JSON. This patch ensures we only use the sanitized values of the array passed in.

Use sanitized values for tax queries

---

adapters/wpcom-vip.php

MySQL on the WordPress.com platform is case insensitive and we're mapping all meta query comparisons to `raw_lc` and we are already normalising strings to lowercase.
But as WP_Meta_Query allows developers to pass arrays of values to some fields (eg.: meta_value), we need to normalise even those arrays, not only strings.
This is related to #11 and was mentioned in Zendesk #51832

wpcom-vip adapter: lowercasing meta queries containing arrays

---

adapters/wpcom-vip.php

The WordPress.com [Elasticsearch Post Document Schema](https://developer.wordpress.com/docs/elasticsearch/post-doc-schema/#es-mapping-post-author) doesn't have `post_author.user_nicename`, so this PR maps it to `author_login`.
This should work in all situations on WordPress.com because we prevent email addresses etc. being used as usernames during signup.
Fixes #46

Update adapter to work with author page queries

---

class-es-wp-query-shoehorn.php

We shouldn't try to shoehorn a query being triggered by ES_WP_Query itself.
If I have a very broad `pre_get_posts` hook:
```
add_action( 'pre_get_posts', function( $query ) {
$query->set( 'es', true );
} );
```
This can end up creating an infinite loop.
1) WP_Query triggers `pre_get_posts` and our callback adds the `es` property
2) `es_wp_query_shoehorn` runs next which picks up the `es` arg and creates an `ES_WP_Query` object.
3) `ES_WP_Query` also triggers `pre_get_posts` which fires our callback and adds the `es` property.
4) `es_wp_query_shoehorn` also runs on this hook and because the `es` arg was set, it creates an `ES_WP_Query` object.
5) And repeat 🔁 
➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ 
➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ 
➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ 
➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ ➿ 
➿ ➿ ➿ ➿ …

Prevent infinite loops! 

---

class-es-wp-query-shoehorn.php

This fix means that the intention of the original query isn't overridden by `es-wp-query`, and means that all forms of post status are viewable if intended.
Fixes #61

Replace 'any' with query vars for type and status

---

tests/query/loggedIn.php

If core has more than 10 post statuses, these tests were failing

Fix broken unit tests in latest versions of WP

---

class-es-wp-query-shoehorn.php

On WordPress.com HyperDB analyzes the query to figure out which database server to connect to. If it can't find a table but the query exists it will throw a PHP warning. This change only adds a comment to the sql query if the query exists.

Only add a comment if the query exists

---

class-es-wp-query-shoehorn.php

Resolve issue #18 where posts_per_page is being set to the default option value vs the value calculated by theme/plugin filters.

Update the  logic to use posts_per_page of query vs option

---

adapters/wpcom-vip.php

It is possible for ES_WP_Query to be called when no index is activated or exists for a site. This update explicitly checks for the index before attempting to call `es_api_search_index`

wpcom adapter :: check for valid index

---

adapters/wpcom-vip.php

Advanced Post Cache and es-wp-query do not work well together. In particular, the WP_Query->found_posts attribute gets corrupted when using both of these plugins, so here we disable Advanced Post Cache completely when queries are being made using Elasticsearch.

WPCOM Adapter : Disable Advanced Post Cache

---

adapters/wpcom-vip.php
class-es-wp-tax-query.php

Create a `es_tax_query_term_{$clause['field']}` term filter allowing for normalization of terms for field mappings.
Also apply filter to wpcom adapter.

Allow adapters to normalize term value (like `strtolower` if mapping to `raw_lc`).

---

class-es-wp-meta-query.php
class-es-wp-query-wrapper.php
tests/query/metaQuery.php

WP_Query supports specifying meta-queries such as the following, where $args are the
arguments to WP_Query() :
$args['meta_query'][]['pv_date'] = array(
'key' => 'pv_date',
'type' => 'NUMERIC',
'compare' => 'EXISTS',
);
$args['meta_query'][]['pv_count'] = array(
'key' => 'pv_count',
'type' => 'NUMERIC',
'compare' => 'EXISTS',
);
Currently these are processed correctly by es-wp-query, but associated
ordering clauses are not, for instance:
$args["orderby"] => Array(
"pv_date" => "desc",
"pv_count" => "desc"
);
This is because sorting-arguments are filtered, so unrecognised ones are left
out. However, that process does not include meta-queries that are specified as shown
above, with the result that the sorting arguments are ignored.
The patch will ensure processing of these meta-queries, and …

More compatibility with WP_Query, when sorting using meta-query keys

---

adapters/jetpack-search.php

In Jetpack Search, it is possible to change the ES query directly using the `jetpack_search_es_query_args` filter. However, since `es_query()` method is calling the `search()` method of `Jetpack_Search`, this filter never runs, therefore any changes to the ES query will not work. By filtering the `$es_args` with `jetpack_search_es_query_args`, we can be sure that any changes to the query will be honoured.
As a side note, `jetpack_search_es_query_args` filter expects the first argument to be a ES query, and the second argument to be a WP_Query object, so it's possible to reuse this filter directly here without any issues. 
Related: https://developer.jetpack.com/hooks/jetpack_search_es_query_args/

Filter `$es_args` in Jetpack Search adapter

---

class-es-wp-query-wrapper.php

Apply the `es_query_use_source` filter in the `get_posts` function to ensure that the source fields are returned properly when needed.

Ensure we can return just the _source fields if desired

---

class-es-wp-query-shoehorn.php

Reproduction
===
- Ensure WP sitemaps is enabled
- Offload pages to ES:
```
function page_es_offload( $query ) {
if ( $query->is_main_query() && $query->is_page() ) { // Conditions to offload to ES.
$query->set( 'es', true );
}
}
add_action( 'pre_get_posts', 'page_es_offload' );
```
- Visit /sitemap.xml
Expectation
===
When Accessing `sitemap.xml`, it should redirect to `wp-sitemap.xml`: https://github.com/WordPress/WordPress/blob/5.8.1/wp-includes/sitemaps/class-wp-sitemaps.php#L237
Actual
===
Accessing `sitemap.xml` leads to a 404 because it doesn't redirect due to lack of `pagename` sanitization, as the value ends up being `sitemap.xml` rather than `sitemap-xml`: https://github.com/WordPress/WordPress/blob/5.8.1/wp-includes/class-wp-query.php#L2062
Reported: …

Prevent sitemap.xml from 404ing

---

adapters/jetpack-search.php

Jetpack 10.6 adapted the class structure for Jetpack Search.
`Jetpack_Search` will be brought up in the next release as a fallback, but as the product evolves, including potential decoupling from Jetpack, utilizing the namespace class will provide a future-proof experience.

Update to current Jetpack Search class

---

composer.json

This PR adds a composer.json file that describes the package and sets its type to `wordpress-plugin`, which enables installation via Composer.

Add composer.json to describe the package

---

.gitignore
class-es-wp-query-wrapper.php

Add support for more complicated `post_mime_type` queries. A query can have a valid mime type (such as `application/pdf`), a prefixed type (such as `image`), OR a combination of both. The latter was failing and only returned the incorrect attachments. 
For example, this was the search results for a query of `image`, `video/mp4`, and `video/oog` (note the missing images):
Expected result:
The more complicated combination of explicit mime type and prefix mime types was converted to a bool query where as the other types of queries were converted to a filter.

Handle more complicated mime queries

---

class-es-wp-query-wrapper.php

This addresses a [breaking change in ES 7.x](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/breaking-changes-7.0.html#_the_filter_context_has_been_removed) that's gone unnoticed.

Add minimum_should_match for mime query

---

class-es-wp-tax-query.php

Re-key array after filtering before JSON encoding

---

class-es-wp-tax-query.php

This updates `ES_WP_Query::transform_query()` to match WordPress core's latest updates, which is a significant improvement.
Resolves #103.

Fix bug with tax queries by name with children

---

adapters/jetpack-search.php

The expected value for the classic search initializer is the site's wpcom ID, not its multisite blog ID.
The issue only appears when Jetpack's Instant Search module is enabled, which prevents the Classic_Search singleton from being first initialized. When initializing through the ES_WP_Query it's misconfigured and fails to perform requests.

fix: jetpack search initializer blog id
